services:
  postgres:
    image: postgres:15
    container_name: study_storybook_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: study_storybook_db
      POSTGRES_USER: storybook_user
      POSTGRES_PASSWORD: storybook_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: study_storybook_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@study-storybook.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  app_network:
    driver: bridge
